### ISSUE TITLE
Throws the error 

### ISSUE THREAD

**Issue by CodeZ1LLa** [PrinceS25/StockAlertBot#2]
It throws the error and I'm not sure what does it mean:

(node:556) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of TypeError
    at Object.writeFile (fs.js:1436:5)
    at writeErrorToFile (file:///C:/Users/Admin/Desktop/InventoryAlertBot-main/InventoryAlertBot-main/stores/newegg.js:22:8)
    at Timeout.newegg [as _onTimeout] (file:///C:/Users/Admin/Desktop/InventoryAlertBot-main/InventoryAlertBot-main/stores/newegg.js:62:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PrinceS25** [comment]
Could you tell me the URLs and other settings you have?

**Comment by PrinceS25** [comment]
This error has to do with the writeErrorToFile function in newegg.js. The "error" variable is not of the expected type so that means something is passing it unexpected type at either line 39 or 62.

**Comment by CodeZ1LLa** [comment]
It seems to be on Newegg's side. The bot itself works great.

**Comment by PrinceS25** [comment]
I think I found a way to fix this error. I'll update the bot soon, perhaps tomorrow.

**Comment by PrinceS25** [comment]
Fixed in #4
