### ISSUE TITLE
Newegg Error

### ISSUE THREAD

**Issue by aRealBanana** [PrinceS25/StockAlertBot#21]
After running the code, the first run completes fine and it shows what is in/out of stock which is very nice.

But after that when it starts looping every INTERVAL time, it keeps getting this error from the logNewegg.log

TypeError: Cannot read property 'innerHTML' of undefined
    at Timeout.newegg [as _onTimeout] (file:///C:/Users/Desktop/StockAlertBot-main/stores/newegg.js:48:71)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by PrinceS25** [comment]
Could you post a screenshot of the console and the URLs you're using?

**Comment by aRealBanana** [comment]
### So this is the console 


![image](https://user-images.githubusercontent.com/47155982/104447156-788a5680-55ac-11eb-800d-efed40eab536.png)
### and those are the URLs
const URLS = [
 
    "https://www.newegg.com/global/kw-en/p/pl?d=3060ti",
    "https://www.newegg.com/global/kw-en/Product/ComboDealDetails?ItemList=Combo.4215928&quicklink=true",
    "https://www.newegg.com/global/kw-en/gigabyte-geforce-rtx-3060-ti-gv-n306tgamingoc-pro-8gd/p/N82E16814932376?Description=3060ti&cm_re=3060ti-_-14-932-376-_-Product&quicklink=true",
    "https://www.newegg.com/global/kw-en/msi-geforce-rtx-3060-ti-rtx-3060-ti-gaming-x-trio/p/N82E16814137611?Description=3060ti&cm_re=3060ti-_-14-137-611-_-Product&quicklink=true",
    //"https://www.newegg.com/global/kw-en/msi-geforce-rtx-3060-ti-rtx-3060-ti-ventus-2x-oc/p/N82E16814137612?Description=3060ti&cm_re=3060ti-_-14-137-612-_-Product",
    //"https://www.newegg.com/global/kw-en/gigabyte-geforce-rtx-3060-ti-gv-n306teagle-oc-8gd/p/N82E16814932378?Description=3060ti&cm_re=3060ti-_-14-932-378-_-Product",
    //"https://www.newegg.com/global/kw-en/evga-geforce-rtx-3060-ti-08g-p5-3667-kr/p/N82E16814487537?Description=3060ti&cm_re=3060ti-_-14-487-537-_-Product",
    //"https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664?Item=N82E16819113664",
    //"https://www.newegg.com/global/kw-en/zotac-geforce-rtx-3060-ti-zt-a30610h-10m/p/N82E16814500507?Description=3060ti&cm_re=3060ti-_-14-500-507-_-Product",
    //"https://www.newegg.com/global/kw-en/gigabyte-geforce-rtx-3060-ti-gv-n306tgaming-oc-8gd/p/N82E16814932377?Description=3060ti&cm_re=3060ti-_-14-932-377-_-Product",
    //"https://www.newegg.com/global/kw-en/gigabyte-geforce-rtx-3060-ti-gv-n306taorus-m-8gd/p/N82E16814932375?Description=3060ti&cm_re=3060ti-_-14-932-375-_-Product",
	//"https://www.newegg.com/global/kw-en/zotac-geforce-rtx-3060-ti-zt-a30610e-10m/p/N82E16814500506?Description=3060ti&cm_re=3060ti-_-14-500-506-_-Product",
	//"https://www.newegg.com/global/kw-en/gigabyte-geforce-rtx-3060-ti-gv-n306teagle-8gd/p/N82E16814932379?Description=3060ti&cm_re=3060ti-_-14-932-379-_-Product",
	//"https://www.newegg.com/global/kw-en/Product/ComboDealDetails?ItemList=Combo.4215927",
	//"https://www.newegg.com/global/kw-en/Product/ComboDealDetails?ItemList=Combo.4215929",
	//"https://www.newegg.com/global/kw-en/Product/ComboDealDetails?ItemList=Combo.4215926",
	//"https://www.newegg.com/global/kw-en/Product/ComboDealDetails?ItemList=Combo.4215925",
	//"",
]


### As you can see the first run is always fine, but when looping I start getting this in the log file

TypeError: Cannot read property 'innerHTML' of undefined
    at Timeout.newegg [as _onTimeout] (file:///C:/Users/alsaf/Desktop/coding/StockAlertBot-main/stores/newegg.js:48:71)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Jeisonx** [comment]
The issue is being caused by the first URL "https://www.newegg.com/global/kw-en/p/pl?d=3060ti" as is not an actual product URL it Cannot read property the innerHTML. From what I can see that URL is a search of the keywords 3060ti. Removing that first URL should fix your issue.

**Comment by aRealBanana** [comment]
Oh, yeah that seems to be the problem. 
Thanks !
