### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by aRealBanana** [PrinceS25/StockAlertBot#23]
So now the script checks every INTERVAL time, is there a way to increase the delay between each URL check? lets say I want to check every 5 minutes for 5 URLS but not instantly search them all, search the first and then wait 5 seconds and then search for the second and so on?
Am suggesting that because it seems like newegg detects if the script check rapidly for large number of URLS and blocks almost all other than the first URL.

**Comment by PrinceS25** [comment]
Yes, it is possible and Amazon checking is implemented in such a way. The issue with that, however, is that if your `INTERVAL` is 5 seconds, then the maximum URLs  you can have per website is 12 before you end up with the same behavior. No doubt it's better than sending 12 requests around the same time but it's tedious to implement.

After I add a GUI for the program, I will definitely look into that.
