### ISSUE TITLE
Suggetion

### ISSUE THREAD

**Issue by twituserjosh** [PrinceS25/StockAlertBot#27]
Being able to use a proxy list would be great here, i keep getting soft banned on amazon and bestbuy even at high refresh rates.
I already pay for proxies for my home network for various things, and i think it would be a great addition here (:

**Comment by PrinceS25** [comment]
Will do, sir. Would you rather put them all , one per line, in a file called `proxies.txt` or would you like to specify what the file is called.

**Comment by twituserjosh** [comment]
yeah 1 per line (proxies.txt)

**Comment by PrinceS25** [comment]
Do all of your proxies have a port of 80. If so, is it possible for it to have a different port?

**Comment by twituserjosh** [comment]
theyre all port :8080

theyre also formatted like so :

ip:port:username:password

**Comment by PrinceS25** [comment]
Do you mind testing it out with a newegg link before I make the change to every store?

**Comment by twituserjosh** [comment]
sure

**Comment by PrinceS25** [comment]
I pushed an update to https://github.com/PrinceS25/StockAlertBot/tree/proxies
It only works on Newegg at the moment. Please try it out with your proxies and let me know what happens.

**Comment by twituserjosh** [comment]
been running for a while with 36 proxies (assuming it rotates on a proxy getting banned)

so far no soft ban / errors on my end, webhooks are working aswell, id like to see it with amazon since thats the real ban simulator

**Comment by twituserjosh** [comment]
^ at a 6 second interval btw, so im pleased with this, thats a massive upgrade that you can run that quickly, before was running at about 45s and getting soft banned on sites

**Comment by PrinceS25** [comment]
Will do, sir! Expect it on all supported sites either today or tomorrow. Please share and consider donating so I can devote more time to this!

**Comment by PrinceS25** [comment]
@twituserjosh Thank you for the donation ❤️. Just letting you know I added proxy support to all stores. It has yet to be tested but feel free to try it out and let me know if there's problems: https://github.com/PrinceS25/StockAlertBot/tree/proxies
