### ISSUE TITLE
Testing with other products

### ISSUE THREAD

**Issue by Danielcarv12** [PrinceS25/StockAlertBot#31]
Hi there, i tried to test the program by using an amazon  and an argos item that are available on the respective websites but I did not get the notification or the sound. Will this only work with the PS5 products or is there something that i am missing. Thank you.

**Comment by PrinceS25** [comment]
It should work with any product provided that you have a link. What notification are you referring you in particular (console text, discord, email, etc.)? Which terminal/console are you using? Can you provide the links you've tried?

**Comment by Danielcarv12** [comment]
T think i figured out what was wrong. Im using amazon UK which calls the "add to cart" button "add to Basket". I had to change the work cart to basket in the amazon.js file and now it works fine. It was telling me that there was no stock for an item that was available but its all good now. Thank you

**Comment by PrinceS25** [comment]
oh I see. Thanks for letting me know. I will fix it. May I have a url for Amazon UK ?

**Comment by Danielcarv12** [comment]
Digital - https://www.amazon.co.uk/dp/B08H97NYGP 
Standard - https://www.amazon.co.uk/dp/B08H95Y452

**Comment by PrinceS25** [comment]
Thank you. I updated it so it *should* work with any language.
