### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by mkinare** [PrinceS25/StockAlertBot#32]
Running the bot overnight gave this error in around 12 hours for all stores.
TypeError: Cannot read property 'status' of undefined
    at file:///D:/github/StockAlertBot/stores/amazon.js:29:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async amazonItem.amazon [as storeFunc] (file:///D:/github/StockAlertBot/stores/amazon.js:24:19)

TypeError: Cannot read property 'status' of undefined
    at file:///D:/github/StockAlertBot/stores/bestbuy.js:30:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.bestbuy [as _onTimeout] (file:///D:/github/StockAlertBot/stores/bestbuy.js:28:19)

TypeError: Cannot read property 'status' of undefined
    at file:///D:/github/StockAlertBot/stores/gamestop.js:29:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.gamestop [as _onTimeout] (file:///D:/github/StockAlertBot/stores/gamestop.js:27:19)

TypeError: Cannot read property 'status' of undefined
    at file:///D:/github/StockAlertBot/stores/newegg.js:32:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.newegg [as _onTimeout] (file:///D:/github/StockAlertBot/stores/newegg.js:27:19)

TypeError: Cannot read property 'status' of undefined
    at file:///D:/github/StockAlertBot/stores/target.js:36:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.target [as _onTimeout] (file:///D:/github/StockAlertBot/stores/target.js:31:19)

My current config is,

{
    "URLS": [
        "https://smile.amazon.com/PlayStation-5-Digital/dp/B08FC6MR62/ref=sr_1_1?dchild=1&keywords=ps5+console&qid=1611437087&rnid=2941120011&s=videogames&sr=1-1",
        "https://www.bestbuy.com/site/sony-playstation-5-digital-edition-console/6430161.p?skuId=6430161&irclickid=zhYRky1LbxyLUYB05-R4sULoUkERWu2JzSY7UU0&irgwc=1&ref=198&loc=Troposphere%20LLC&acampID=0&mpid=62662",
        "https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5-digital-edition/11108141.html?condition=New&utm_source=rakutenls&utm_medium=affiliate&utm_content=NowInStock&utm_campaign=10&utm_kxconfid=tebx5rmj3&cid=afl_10000087&affID=77777&sourceID=AKGBlS8SPlM-5eqfSig1IJArHmsNtRCcuA",
        "https://www.target.com/p/playstation-5-digital-edition-console/-/A-81114596?clkid=1fdd97cbNeb2311eaa25642010a246e2a&lnm=115444&afid=Troposphere%20LLC&ref=tgt_adv_xasd0002#lnk=sametab",
        "https://www.newegg.com/p/N82E16868110295"
    ],
    "SUPPORTED_STORES_DOMAINS": [
        "amazon",
        "antonline",
        "argos",
        "bestbuy",
        "costco",
        "currys",
        "gamestop",
        "microcenter",
        "newegg",
        "target",
        "tesco",
        "tescopreorders",
        "playstation"
    ],
    "INTERVAL": {
        "unit": "minutes",
        "value": 5
    },
    "OPEN_URL": true,
    "ALARM": true,
    "AMAZON_DELAY": 60,
    "TARGET_ZIP_CODE": "12020",
    "TARGET_KEY": "ff457966e64d5e877fdbad070f276d18ecec4a01",
    "EMAIL": true,
    "WEBHOOK_URLS": [],
    "SUPPORTED_WEBHOOK_DOMAINS": [
        "discord",
        "slack"
    ]
}

I am in NY.

Thanks and regards,
Resh

**Comment by PrinceS25** [comment]
Did it error occur more than once? If so, how many times? Did it work after you restarted the program?

**Comment by mkinare** [comment]
No, the error has not occurred again. I have moved the app to an ec2 instance today and will update you again if this error occurs again. I have a suspicion if my desktop going to sleep was a reason why this might have happened.

**Comment by PrinceS25** [comment]
Then this is totally normal to have the error occur once in a while. I will close the issue but let me know if it occurs more frequently. Please share and consider donating so I can devote more time to this!
