### ISSUE TITLE
Argos Does not work

### ISSUE THREAD

**Issue by jeffmcjeffers0n** [PrinceS25/StockAlertBot#33]
Hello, the argos store does not work. Nothing is printed out no matter what product you put in...  Thanks

**Comment by PrinceS25** [comment]
Can you give me a link you're trying? Does it just hang?

**Comment by PrinceS25** [comment]
@Jeisonx may have fixed the problem in the latest update. Please try it again and let us know.

**Comment by jeffmcjeffers0n** [comment]
Hello, will send info soon

**Comment by jeffmcjeffers0n** [comment]
So i have two links in there. One for amazon and one for argos. The one for argos that I have is a placeholder, I believe it is a doll. The function is run every time but nothing happens. 
![image](https://user-images.githubusercontent.com/69084614/105677995-844b1680-5ee4-11eb-93a9-2b8b77e39b17.png)

**Comment by jeffmcjeffers0n** [comment]
Sorry! just saw the new argos commit. It appears to be working! Thanks! Will let you know if not!

**Comment by PrinceS25** [comment]
Good to hear that!! Let me know if there's any more issues.
Please share and consider donating if my project helps you out and I will devote more time to this!
