### ISSUE TITLE
dotenv.config is not a function

### ISSUE THREAD

**Issue by CodeProjector** [PrinceS25/StockAlertBot#34]
```
c:\StockAlertBot>npm start

> stock-alert-bot@2.0.0 start c:\StockAlertBot
> node main.js

file:///c:/StockAlertBot/utils/config.js:2
dotenv.config();
       ^

TypeError: dotenv.config is not a function
    at file:///c:/StockAlertBot/utils/config.js:2:8
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stock-alert-bot@2.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stock-alert-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James\AppData\Roaming\npm-cache\_logs\2021-01-26T23_45_16_239Z-debug.log
```     

Any fix?

**Comment by PrinceS25** [comment]
Hi. Did you run `npm install`? If so, what is your node version? You can check by running `node -v`.

**Comment by CodeProjector** [comment]
> Hi. Did you run `npm install`? If so, what is your node version? You can check by running `node -v`.

Yes, node js v14.15.4

**Comment by PrinceS25** [comment]
Can you check whether an `.env` file is present at the root  directory?

**Comment by CodeProjector** [comment]
> Can you check whether an `.env` file is present at the root directory?

Yes ```.env``` is present within the root

**Comment by SeanPagani** [comment]
Not working for me as well, same error. Windows 10, same node js version same env at root

**Comment by SeanPagani** [comment]
@PrinceS25 Fixed the issue, all you need to do is remove the semi colon from utils\config.js
import dotenv from 'dotenv'
dotenv.config()

export default {
	email: {
		service: process.env.EMAIL_SERVICE,
		from: process.env.EMAIL_FROM,
		pass: process.env.EMAIL_PASS,
		to: process.env.EMAIL_TO
	}
}

**Comment by Jeisonx** [comment]
@CodeProjector Would you mind trying @SeanPagani solution if it works I can push a fix.

**Comment by CodeProjector** [comment]
> @CodeProjector Would you mind trying @SeanPagani solution if it works I can push a fix.

Hi I tested it... this is the result of the above fix

```C:\Users\James>cd c:\

c:\>cd stockalertbot

c:\StockAlertBot>npm start

> stock-alert-bot@2.0.0 start c:\StockAlertBot
> node main.js


c:\StockAlertBot>```

**Comment by SeanPagani** [comment]
strange. here's my output. it takes about 20 seconds before the stock shows up.
> stock-alert-bot@2.0.0 start C:\Users\smp20\Desktop\StockAlertBot-main
> node main.js

(node:4664) ExperimentalWarning: The ESM module loader is experimental.
11:43:36 AM: "MSI - NVIDIA Geforce RTX 3080 VENTUS 3X 10G OC BV - GDDR6X - PCI Express 4.0 - Graphic Card - Black/Silver" not in stock at Best Buy. Will keep retrying in background every 10 seconds
11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in stock at Best Buy. Will keep retrying in background every 10 seconds
11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 BLACK GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in stock at Best Buy. Will keep retrying in background every 10 seconds
11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 ULTRA GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in

**Comment by CodeProjector** [comment]
> strange. here's my output. it takes about 20 seconds before the stock shows up.
> 
> > stock-alert-bot@2.0.0 start C:\Users\smp20\Desktop\StockAlertBot-main
> > node main.js
> 
> (node:4664) ExperimentalWarning: The ESM module loader is experimental.
> 11:43:36 AM: "MSI - NVIDIA Geforce RTX 3080 VENTUS 3X 10G OC BV - GDDR6X - PCI Express 4.0 - Graphic Card - Black/Silver" not in stock at Best Buy. Will keep retrying in background every 10 seconds
> 11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in stock at Best Buy. Will keep retrying in background every 10 seconds
> 11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 BLACK GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in stock at Best Buy. Will keep retrying in background every 10 seconds
> 11:43:36 AM: "EVGA - GeForce RTX 3080 XC3 ULTRA GAMING 10GB GDDR6 PCI Express 4.0 Graphics Card" not in

Yeah mine doesnt even do that it cancels it right after `> stock-alert-bot@2.0.0 start c:\StockAlertBot
> node main.js`

**Comment by franbueno** [comment]
I had the same problem. Just update node to the latest version. It'll work :)

**Comment by PrinceS25** [comment]
Thanks everyone for contributing! 
@CodeProjector, is your original problem (dotenv.config is not a function) solved by adding a semicolon?

**Comment by CodeProjector** [comment]
Issue was resolved. Needed to reinstall everything from start, including windows 10

**Comment by madscorpio20** [comment]
i wa also getting same issue problem was that i had  written port = 8000 instead of const port = 8000

**Comment by memanesavita** [comment]
I got a error when I try to access env file.


dotenv.config();
       ^

TypeError: dotenv.config is not a function
    at Object.<anonymous> (/home/savita/Desktop/TODO_API/index.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.0.0
[nodemon] app crashed -

**Comment by mortezae** [comment]
If anyone encounters this in future, he/she probably used `process.env.somthing` before a code snippet that probably is a IIFE, which is one of cases that you have to use semicolon at the end of line.
