### ISSUE TITLE
Amazon Error 503 and Proxies 

### ISSUE THREAD

**Issue by aRealBanana** [PrinceS25/StockAlertBot#37]
Although I have more than 90 proxies, yet I keep getting 503 a lot, I think the same proxy sometimes is being used for more than one amazon link per Interval time am not sure. Increasing Interval makes it get less 503 error yet it still gets it.

**Comment by PrinceS25** [comment]
The proxies are chosen at random and bad ones are placed in a " not to use" list. Are you using the latest version? It could also be that the proxies you're using are being used by others to reach Amazon. Where did you get the proxies?
