### ISSUE TITLE
only starts once

### ISSUE THREAD

**Issue by JDuggal760** [PrinceS25/StockAlertBot#39]
I can only see the interval and what's it going for once it doesn't come up multiple times
![githelp](https://user-images.githubusercontent.com/77640905/106979871-2fea3700-672d-11eb-8b4d-e93d7ea054dd.PNG)
just like that 
is it normal???

**Comment by PrinceS25** [comment]
Hi! Please refer to #5 : https://github.com/PrinceS25/StockAlertBot/issues/5#issuecomment-751171453
