### ISSUE TITLE
says to report this to github

### ISSUE THREAD

**Issue by JDuggal760** [PrinceS25/StockAlertBot#40]
![gitreport](https://user-images.githubusercontent.com/77640905/106981393-ee0ec000-672f-11eb-9a6f-f670994575a5.PNG)
supposed to report this to GitHub

**Comment by PrinceS25** [comment]
Could you please post bestbuy.log located in the logs folder? Also, in which country are you located?

**Comment by JDuggal760** [comment]
USA 
where are the logs gonna be

**Comment by PrinceS25** [comment]
logs should be in the "logs" folder of wherever you launch the program.

**Comment by PrinceS25** [comment]
Hi @JDuggal760 !
Is this still a problem? If not, would you kindly close the issue?
