### ISSUE TITLE
Web Settings issue

### ISSUE THREAD

**Issue by furiaceka87** [PrinceS25/StockAlertBot#41]
When I run **npm run settings** command I get the correct answer from terminal:
```
> stock-alert-bot@2.0.0 settings
> node server/index.js
Setting up server...
Looking for .env file...
.env file found! Attempting to read...
Importing important stuff...
Starting server...
Setting up routes...
Opening settings page...
Server started!
```

But when I go to the setting page (ip:3250) I cannot add links and I have empty settings page.
[https://ibb.co/fQb2bb1](https://ibb.co/fQb2bb1)
[https://ibb.co/gDkmH2M](https://ibb.co/gDkmH2M)

I have any error when I try to add link, but simply not possible to add it. I've also tried to give 777 permission to the installation folder without any change.

**Comment by PrinceS25** [comment]
Hi. Which browser are you using to access localhost:3250? 
If it's Firefox or Chrome, could you post a screencap of the console in the DevTools (Chrome) or Developer Tools (Firefox)?

**Comment by furiaceka87** [comment]
Here it is the screenshot using chrome:
[https://ibb.co/wz1952k](https://ibb.co/wz1952k)

**Comment by furiaceka87** [comment]
Thanks to PrinceS25 I solved the issue.
I've changed localhost with my server IP or address in server/index.html on line 807, 814, 825 and 842.
`http://MYSERVERADDRESS:3250/config` instead of `http://localhost:3250/config`
