### ISSUE TITLE
Currys (UK)

### ISSUE THREAD

**Issue by NathanCoder21** [PrinceS25/StockAlertBot#44]
Hello,

Great bot so far, a minor tweak is that the bot thinks Curry's items are in stock as it says "Available for collection" on all their items, is there a wait to check for "Available for delivery" only?

**Comment by PrinceS25** [comment]
Hi Nathan,
Currently the bot checks if the button says, "Add to basket". I'm not quite sure what made you think it checks for "Available for collection". Being in the US, I actually don't see "Available for collection" or "Available for delivery" on any of item pages. Could you perhaps provide a screenshot? https://github.com/PrinceS25/StockAlertBot/blob/88261507a4d2c4eb3cff02928e2f5d31717822ab/stores/currys.js#L78

**Comment by PrinceS25** [comment]
Will close due to inactivity. Please let me know if you have further questions.
