### ISSUE TITLE
Discord alert not working?

### ISSUE THREAD

**Issue by EspadaXVl** [PrinceS25/StockAlertBot#46]
I have gotten my webhook an implement into the config.js file but the program still send an alert on discord. I have attached an image with the error.

![image](https://user-images.githubusercontent.com/80026502/110086935-9e380e80-7d58-11eb-828b-507e2fa4498d.png)

**Comment by PrinceS25** [comment]
Thanks for reporting! Please redownload as it's been fixed in 13abdd256df876171eebd5ba2b19c8095bec62e0 😄
