### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Lukemul6** [PrinceS25/StockAlertBot#6]
```
internal/modules/cjs/loader.js:1149
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Luke\Downloads\StockAlertBot-main\StockAlertBot-main\main.js
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:977:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
  ```

**Comment by PrinceS25** [comment]
You sure you followed all of the steps correctly? If so, try running it like this `node --experimental-modules main.js`

**Comment by Lukemul6** [comment]
Perfect, that worked! Is there any way to disable the beeping and opening the webpages? I literally just want it to send to discord.

**Comment by PrinceS25** [comment]
As of right now, you can only disable the opening of the webpages by setting `OPEN_URL` in main.js to `false`. 
I'll add the ability to disable beeps in the near future!

**Comment by Lukemul6** [comment]
All good. I managed to disable the beeps. I am trying to add images now and making the webhooks send embeds.

**Comment by PrinceS25** [comment]
If you know how and if it works out, you may do a pull request so I can add those features in.

**Comment by PrinceS25** [comment]
Just letting you know that I *officially* added the ability to toggle beeps

**Comment by Lukemul6** [comment]
Thank you! I sent you an email btw :)
