### ISSUE TITLE
Best Buy is not working

### ISSUE THREAD

**Issue by Bilalsh4h** [PrinceS25/StockAlertBot#8]
I have entered best buy links but unfortunately it is not working. It's only showing the New Egg links I have entered.

**Comment by PrinceS25** [comment]
Could you provide a screenshot of the program running as well as some of the Best Buy links you're trying?

**Comment by Tobraza** [comment]
I really need this to work for best buy lol

**Comment by PrinceS25** [comment]
I'll test some Best Buy links out and fix if it's not working

**Comment by PrinceS25** [comment]
Best Buy is *hopefully* fixed in db7d672cfd59a0cc28d5d40745d59e1f8c68ea70
Let me know if it still causes problems
